### PR TITLE
mini SV bits

### PR DESCRIPTION
**Pull request by Srheft**
This is just to add mini SV bits before an upcoming PR. I didn't want to combine this with another PR that could get voted off.

### CODE REVIEW

**Comment by sbailey** [comment]
@tskisner you had mentioned to me PR difficulty with compiling cfitsio via pip, which is impacting tests of this PR too.  Do you have a workaround?  Also mentioning @weaverba137 as another one of our "get travis installation stuff sorted out" experts.  Help?

The code changes in this PR looks fine.  Thanks.  They require desihub/desitarget#590 which has already been merged.

**Comment by tskisner** [comment]
The symptom I saw in a fiberassign branch was that `pip install --no-binary :all: fitsio` failed to compile the internal cfitsio.  I'll try to fix that in the fiberassign branch first (https://github.com/desihub/fiberassign/tree/extend_qa) before recommending a change here.

**Comment by tskisner** [comment]
This issue (and the one in the fiberassign CI) is exactly the one reported on the upstream fitsio repo:

https://github.com/esheldon/fitsio/issues/288

I'll add to that thread.

**Comment by tskisner** [comment]
Ok, I cherry-picked the travis fix from #253 and tests pass here too.  Will merge shortly.

**Pull request merged**
