### PR TITLE
Use a dynamic focalplane model

### PR DESCRIPTION
**Pull request by tskisner**
This work removes many hard-coded properties and makes use of the newly-added desimodel.io.load_focalplane() to retrieve all positioner properties and the exclusion polygons to use for each positioner.

Opening this PR to more easily track comments and changes.  Do not merge yet.

### CODE REVIEW

**Comment by tskisner** [comment]
Ok, this branch is now re-based against master (which was just tagged 1.0.4).

**Comment by tskisner** [comment]
I believe this branch is ready to merge.  This code currently **requires** a recent version of desimodel (>= 0.9.2).  In order to use the lastest hardware model, you also need the current trunk of the desimodel data svn.  Desimodel svn now includes two hardware models (at least one more will be added in the coming weeks).  The run time passed to `fba_run` (default is current time) determines which hardware model is selected.  To use the old model, select a date prior to 2019-09-16.  Here is a comparison of the old and new focalplanes showing the positioners at the zero point of their theta range and at the zero angle of their phi range plus PI.  Also plotted are the default exclusion polygons:

[test_focalplane_compare.pdf](https://github.com/desihub/fiberassign/files/3633288/test_focalplane_compare.pdf)

In addition to the unit tests, I have run this on about 300 tiles of DR7.1 comparing the output of master with this branch using the new hardware model.  In that comparison there are noticeably fewer science targets assigned per petal with this new hardware model.  This is likely due to:

1.  The realistic exclusion polygons are larger than the historic ones used originally in fiberassign.
2.  Realistic positioners may not be able to reach the very center of the patrol disc due to different arm lengths.

The new realism here is just something we have to deal with.  It remains to be seen if the assignment efficiency can be improved as part of the work on #176, #179, #183, and #184.

**Comment by sbailey** [comment]
@Srheft has independently run this (thanks!) and verified that it doesn't fundamentally break things, though there are slightly fewer science assignments due to the increased exclusion zones causing more collisions to avoid (oh well, that is reality).  Merging now.

**Comment by sbailey** [comment]
@tskisner please update doc/changes.rst in master with a summary of the changes in this PR.  Thanks.

**Pull request merged**
