### PR TITLE
added plot to qa-fiberassign

### PR DESCRIPTION
**Pull request by akrolewski**
Added plot capability to qa-fiberassign using code used to produce Fig. 3 in https://arxiv.org/pdf/1809.07355.pdf.
Also restructured arguments so that qa-fiberassign takes a file with a list of tilefiles as input rather than a list of tilefiles directly (in case you want to run many tiles at once).

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks for adding the code to make that plot.

Please update the arguments so that if you give it `--tilefile` it will use that, but otherwise it still lets you do `qa-fiberassign tile*.fits` too.

Please also update it so that if you don't provide `--plotdir`, then it won't spend the time making and saving N>>1 plots.

Does this produce meaningful output on bright time tiles that may not have any ELG, LRG, or QSO targets?

**Comment by michaelJwilson** [comment]
Interest in finishing this off?  

image

image

Can be produced by 
https://github.com/michaelJwilson/fiberassign/blob/master/py/fiberassign/smith.py

**Comment by weaverba137** [comment]
@sbailey, is this branch/PR worth keeping?  I think it would be impossible to merge in its current state.

**Comment by weaverba137** [comment]
@araichoor, same question to you: is this branch/PR worth keeping?

**Comment by araichoor** [comment]
I don t know; that happened before I arrived.
personally, I never used that script, so I don t really know if it s worth it to put effort to bring it in consistency with today s code.
on my side, I won t have time to do that.

maybe @akrolewski has a point of view? (though that s four years old...)

**Comment by araichoor** [comment]
I ll close this PR.
I guess one can still revive the branch+PR if need be.

**Pull request closed without merging**
