### PR TITLE
propagates input information

### PR DESCRIPTION
**Pull request by forero**
This PR implements the solution #96. It doesn't  propagate/compute all the required information in the original issue. Some questions about the best way to implement it remain open. I continue the discussion in #96.

### CODE REVIEW

**Comment by sbailey** [comment]
This PR looks fine, though I see commits very recently so I'm going to wait on merging until you confirm that you are done.  Please point to some example output at NERSC with the commands used to generate it using this branch.  Thanks.

**Comment by forero** [comment]
@sbailey Right. I am still making commits. I will ping you once this PR is ready for review.

**Comment by forero** [comment]
@sbailey Please go ahead and review this PR. I focused on the HDU1 columns. 
Here  I have inputs with the latest format from Adam: `/global/cscratch1/sd/forero/small_dr7.1`

This command should work with the inputs there:
`fiberassign --mtl cut_mtl_dr7.1-PR372.fits --sky cut_skies_dr7.1-0.22.0.fits --stdstar cut_std_dr7.1-PR372.fits --fibstatusfile fiberstatus.ecsv --footprint ./cut_desi_tiles.fits --outdir output_fiberassign/ --gfafile cut_gfas_dr7.1.fits`
 
The implementation in this PR is definitely not backwards compatible.  The script expects the latest `desitarget` format.

**Comment by geordie666** [comment]
I wouldn't be *too* concerned about backwards compatibility. If I run on an older version of the sweeps, it will populate the columns in the new data model. So, if we need DR6/DR5 etc., I can rerun them.

**Comment by sbailey** [comment]
Thanks.  I added some more columns and sped it up by pre-filtering what targets could be on what tiles so that the MTL + fiberassign join now takes <0.1 sec/tile instead of ~5 sec/tile (which would have taken ~14 hours to write all 10k tiles).  Merging now.

**Comment by forero** [comment]
Thanks!

**Pull request merged**
