### PR TITLE
omp master and die on missing surveyFile

### PR DESCRIPTION
**Pull request by rainwoodman**
I don't yet understand the job partition scheme in global.cpp.
But this shall allow us to compile without openmp in a clean way.

If @rncahn  or someone would like to say a few overall words about how OpenMP is used in the code it would be great.

### CODE REVIEW

**Comment by rainwoodman** [comment]
My bad. The threading is trivial. I missed `#pragma omp for ` below. 
Still, this PR gets rid of the requirement of an openmp enabled compiler.

**Comment by rncahn** [comment]
Open MP is used only in "collect_galaxies_for_all"

it provides list of galaxies available to fiber k on tile j: P[j].av_gals[k]

this is in global.cpp

**Comment by rainwoodman** [comment]
This PR are two usability improvements:

- pragma omp master is the proper way of instructing master-only execution in omp parallel sections. This allows the code to compile without -fopenmp.

- the code shall die instead of writing zero output to minimize surprise factor when surveyFile could not be properly opened.

**Comment by sbailey** [comment]
Reassigning to Ted since he is much more knowledgable about omp, C++ compiling, etc. than I am.

**Comment by tskisner** [comment]
This looks fine.  If you ever need access to the exact thread ID (rather than just checking if master with a pragma), then one would have to have a compile time define (e.g. -DHAVE_OPENMP) that is set in the specific platform file, and then guard the "#include <omp.h>" with a #ifdef HAVE_OPENMP.  Anyway, that is not necessary for this simple use of openmp.

**Pull request merged**
