### PR TITLE
Slight changes to build files, and valgrind / compiler cleanup

### LINKED ISSUE #35: fiberassign crashes valgrind.
The main error message is

```
--15909:0: aspacem Valgrind: FATAL: VG_N_SEGMENTS is too low.
--15909:0: aspacem   Increase it and rebuild.  Exiting now.
```

The full log is here:

```
valgrind ../src/fiberassign params_fiberassign.txt 
==15909== Memcheck, a memory error detector
==15909== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==15909== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==15909== Command: ../src/fiberassign params_fiberassign.txt
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x433873: printFile(char const*) (misc.cpp:999)
==15909==    by 0x40380C: main (fiberassign.cpp:32)
==15909== 
Targfile mtl-lite.fits 
SStarsfile stdstars-lite.fits 
SkyFfile  sky-lite.fits 
Secretfile truth-lite.fits 
surveyFile default_survey_list.txt 
tileFile 0.3.1/data/footprint/desi-tiles.par 
fibFile 0.3.1/data/focalplane/fiberpos.txt 
outDir /home/yfeng1/source/fiberassign/test/output/ 

PrintAscii true 
PrintFits false 
diagnose true 

kind QSOLy-a QSOTracer LRG ELG FakeQSO FakeLRG SS SF 
type QSO QSO LRG ELG QSO LRG SS SF 
prio 3400 3400 3200 3000 3400 3200 0 0 
priopost 3500 0 3200 0 0 0 0 0 
goal 5 5 2 1 5 2 5 5 
goalpost 5 1 2 1 1 1 5 5 
lastpass 0 0 0 1 0 0 1 1  
SS       0 0 0 0 0 0 1 0 
SF       0 0 0 0 0 0 0 1  
pass_intervals 0 50 100 150 200 

Randomize false 
Pacman false 
Npass 5 
MaxSS 10 
MaxSF 40 
PlateRadius 1.65 
InterPlate 0 
Analysis 0 
InfDens false 

TotalArea 15789.0 
invFibArea 700 
moduloGal 1 
moduloFiber 1 

Collision false 
Exact true 
AvCollide 3.2 
Collide 1.98 
NoCollide 7.0 
PatrolRad 5.8 
NeighborRad 14.05 

PlotObsTime false 
PlotHistLya false 
PlotDistLya false 
PlotFreeFibHist false 
PlotFreeFibTime false 
PlotSeenDens false 
PrintGalObs false 


MinDec -10. 
MaxDec 10. 
MinRa 0. 
MaxRa 10. 
Verif false 
------------------------------------------------- 
# read target, SS, SF files at 0.141 s
reading MTL file mtl-lite.fits
HDU #2  Binary Table:
Keeping 593965 targets within ra/dec ranges
reading MTL file stdstars-lite.fits
HDU #2  Binary Table:
NUMOBS_MORE not found ... setting to 0
PRIORITY not found ... setting to 0
GRAYLAYER not found ... setting to 0
Keeping 27715 targets within ra/dec ranges
reading MTL file sky-lite.fits
HDU #2  Binary Table:
NUMOBS_MORE not found ... setting to 0
PRIORITY not found ... setting to 0
GRAYLAYER not found ... setting to 0
Keeping 277634 targets within ra/dec ranges
# ... took : 14.9 s
 Target size 593965 
 Standard Star size 621680 
 Sky Fiber size 899314 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x403B89: main (fiberassign.cpp:50)
==15909== 
==15909== Use of uninitialised value of size 8
==15909==    at 0x403BA7: main (fiberassign.cpp:51)
==15909== 
==15909== Use of uninitialised value of size 8
==15909==    at 0x403BC6: main (fiberassign.cpp:51)
==15909== 
==15909== Use of uninitialised value of size 8
==15909==    at 0x403BF5: main (fiberassign.cpp:52)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x403C3E: main (fiberassign.cpp:55)
==15909== 
==15909== Use of uninitialised value of size 8
==15909==    at 0x403C58: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF20CB: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Use of uninitialised value of size 8
==15909==    at 0x5AEE0CB: _itoa_word (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF2610: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AEE0D5: _itoa_word (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF2610: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF268E: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF21A1: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF2741: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF21F3: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
==15909== Conditional jump or move depends on uninitialised value(s)
==15909==    at 0x5AF222A: vfprintf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x5AF8D28: printf (in /usr/lib64/libc-2.22.so)
==15909==    by 0x403C6D: main (fiberassign.cpp:56)
==15909== 
  class  0  number  474347
  class  1  number  68576
  class  2  number  51042
# ... took : 21.3 s
getting file list
 number of tiles 10666 
==15909== Warning: set address range perms: large range [0x395db040, 0x747e6840) (undefined)
 size of P  10666
--15909:0: aspacem Valgrind: FATAL: VG_N_SEGMENTS is too low.
--15909:0: aspacem   Increase it and rebuild.  Exiting now.
```

### PR DESCRIPTION
**Pull request by tskisner**
Tweak makefiles and platform files to work more consistently at NERSC.  Fix bugs related to freeing memory and closing FITS files.  Also improve handling of int vs. unsigned indices.  Clean up some other compiler warnings.

All code now compiles cleanly with "-Wall", and valgrind reports only external warnings from other system libraries.

Closes #35

### CODE REVIEW

**Comment by tskisner** [comment]
This also closes #8

**Comment by tskisner** [comment]
After all the general cleanups and one specific change pushed in the last commit, this branch now builds cleanly on OS X with clang++ using "-std=c++11" (i.e. no gnu extensions needed).  Closes #117

**Comment by forero** [comment]
Working on cori I can get the code to compile with `make platform=nersc_desiconda`, but I get a bunch of messages like this one

```
/opt/gcc/7.2.0/snos/include/g++/bits/vector.tcc(633): (col. 7) remark:_ZNSt6vectorI6targetSaIS0_EE15_M_range_insertIN9__gnu_cxx17__normal_iteratorIPS0_S2_EEEEvS7_T_S8_St20forward_iterator_tag has been targeted for automatic cpu dispatch
```

On `edison` I don't get any of those.  Should I worry?

**Comment by forero** [comment]
Using `make PLATFORM=nersc_gcc` works just fine both on `cori` and `edison`

**Comment by tskisner** [comment]
Hmm, that is strange.  I was using an older desiconda on edison for this test.  Let me go try with the latest one.

**Comment by tskisner** [comment]
Ok, here are some tests on edison.  Using the latest installed desiconda:
```
%>  module use /global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/modulefiles
%>  module load desiconda
```
make produces:
```
make                                                                  
make: Entering directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign'       
make[1]: Entering directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign/src'
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o fiberassign.o -c fiberassign.cpp                                                                                
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o collision.o -c collision.cpp                                                                                    
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o feat.o -c feat.cpp                                                                                              
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o global.o -c global.cpp                                                                                          
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o misc.o -c misc.cpp                                                                                              
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o structs.o -c structs.cpp                                                                                        
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/include -o version.o -c version.cpp                                                                                        
icpc -o fiberassign_exec fiberassign.o collision.o feat.o global.o misc.o structs.o version.o -fopenmp  -L/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib -L/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib -L/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib  -L/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180512-1.2.5-spec/aux/lib  -lcfitsio -lm
make[1]: Leaving directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign/src'
make: Leaving directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign'
```
So no errors in that case.  Trying the "current" desiconda version (the default, which is 20180130-1.2.4-spec) from a clean login I get:
```
%>  module use /global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/modulefiles
%>  module load desiconda
%>  make                                                                  
make: Entering directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign'       
make[1]: Entering directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign/src'
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o fiberassign.o -c fiberassign.cpp                                                                                
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o collision.o -c collision.cpp                                                                                    
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o feat.o -c feat.cpp                                                                                              
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o global.o -c global.cpp                                                                                          
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o misc.o -c misc.cpp
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o structs.o -c structs.cpp
icpc  -O3 -g -fPIC -xAVX -std=c++11 -pthread -fPIC -DPIC -fopenmp -fopenmp -I.  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include  -I/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/include -o version.o -c version.cpp
icpc -o fiberassign_exec fiberassign.o collision.o feat.o global.o misc.o structs.o version.o -fopenmp  -L/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib -L/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib -L/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib  -L/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib -Wl,-R,/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/aux/lib  -lcfitsio -lm
make[1]: Leaving directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign/src'
make: Leaving directory '/scratch2/scratchdirs/kisner/software/git/desi/fiberassign'
```
So I don't see any errors there either.  If you do a "module list" when you see those compile errors, do you have any other fiberassign modules loaded?  What does "which harpconfig" show?

**Comment by tskisner** [comment]
Oh shoot, I see now that you were **working on cori**, not edison.  Just a second and I will try there.

**Comment by tskisner** [comment]
Ok, sorry, I should have read your original message more carefully.  Those messages are just informational from the compiler.  On cori, we are building "fat binaries" that contain optimized machine code for both haswell and KNL, bundled into the same object files and selected at runtime depending on the current architecture.  The Intel compiler is just telling you that it is doing this and setting up the output products to do this runtime dispatch.

**Comment by forero** [comment]
Got it. Things are running fine.

**Pull request merged**
