### PR TITLE
Compute and report sky location (exposure time calculator) for every tile.

### PR DESCRIPTION
**Pull request by forero**
Solves #95. Everything is done within the python wrapper by running `fiberassign_exec` twice.
The final result is a tile file with three tables: `FIBERASSIGN` (5000 fibers), `POTENTIAL` (5000 fibers) and `SKYETC` (20 fibers).

### CODE REVIEW

**Comment by sbailey** [comment]
The following test command works for master but produces no output for this sky branch.  What's missing?
```
basedir=/project/projectdirs/desi/datachallenge/reference_runs/18.3
fiberassign --mtl $basedir/targets/mtl.fits \
    --sky $basedir/targets/sky.fits \
    --stdstar $basedir/targets/standards-dark.fits \
    --fibstatusfile $basedir/fiberassign/fiberstatus.ecsv \
    --surveytiles $basedir/fiberassign/dark-tiles.txt \
    --outdir $SCRATCH/temp/
```

And another reason to use something like `tempfile.mkdtemp`: the user might be running fiberassign in a directory where they don't have write permission and the current branch fails to be able to write its temporary files there.

**Comment by forero** [comment]
@sbailey I have included the `tempfile.mkdtemp` calls.

The problem you found comes from the fact that the `sky.fits` file you use as an input doesn't have a `NUMOBS` column, so `NUMOBS` is set to zero when it's read by `fiberassign`. When I read that file as the target file to be assigned for the `sky` fibers, then nothing gets assigned and the `tile_*.fits` file for those `sky` fibers are not written down. The absence of those files halts the computation of the `tile_*.fits` with the extended `SKYETC` table. I will fix that by setting `NUMOBS` to one if that column is not included in the input file.

**Comment by forero** [comment]
@sbailey Things seem to be working now. Please check again.

**Comment by sbailey** [comment]
Changes look good.  Thanks.  I verified that it works from a directory in which I don't have write permission and that the previously failing example now works.  Merging.

**Pull request merged**
