### PR TITLE
fill unassigned with sky fibers

### LINKED ISSUE #82: fill unused fibers with stdstars and sky
If there are any unused fibers after assigning all available science targets and meeting the standard star and sky fiber minimum requirements, fill any remaining unused fibers with standard stars and sky locations.  "BADSKY" (DESI_TARGET = 2**36) should be used as fillers of last resort (though we don't have these in the current mocks).

The input catalogs should be dense enough that every fiber should always have *something* it can point at.  We should consider it an error condition of the input catalogs if they don't provide that, though for now it would probably be useful if fiberassign would continue to output tile files anyway and let us clean it up after the fact until we are robustly working with sky catalogs that guarantee coverage.

### PR DESCRIPTION
**Pull request by forero**
This change seems to fix #82

### CODE REVIEW

**Comment by sbailey** [comment]
I tried running this on the latest reference run in `/project/projectdirs/desi/datachallenge/reference_runs/18.1/fiberassign` and then checking with `qa-fiberassign tile*.fits`.  It still has the same number of unassigned fibers on the same tiles.  Could you @forero try that as well?

That directory has configuration files, but make sure to update the `outDir` option before running so that you don't accidentally overwrite the reference run.

**Comment by forero** [comment]
@rncahn  I checked that this makes sense in a single tile (at least!). Please take a look at [this notebook](https://github.com/forero/SandboxDESI/blob/908c85ff17b24137beae73c79dfbee97771c0109/fiber/fill_fibers_with_sky.ipynb).

There I run 4 simple experiments (sky targets are always 2000 deg^-2 and standard stars are always 120 deg^-2).

1. Master branch. 100 targets/deg^2. Result: 
```
Assigned TARGETS: 692
Unassigned fibers 3808
Assigned SKY: 400
Unassigned fibers 3808
Assigned STAR: 100
Unassigned fibers 3808
```
2. Master branch. 2000 targets/deg^2. Result:
```
Assigned TARGETS: 4499
Unassigned fibers 1
Assigned SKY: 400
Unassigned fibers 1
Assigned STAR: 100
Unassigned fibers 1
```
3. New branch. 100 targets/deg^2. Result: 
```
Assigned TARGETS: 705
Unassigned fibers 222
Assigned SKY: 3973
Unassigned fibers 222
Assigned STAR: 100
Unassigned fibers 222
```
4. Master branch. 2000 targets/deg^2. Result:
```
Assigned TARGETS: 4500
Unassigned fibers 0
Assigned SKY: 400
Unassigned fibers 0
Assigned STAR: 100
Unassigned fibers 0
```

**Comment by forero** [comment]
@sbailey I will try that. I will check the number of assigned targets per class. The number of unassigned fibers might be the same if the target number densities are high.

**Comment by rncahn** [comment]
Jaime,

This looks good. I had forgotten that the check on whether the limits on SF
and SS had been reached had been taken out of ok_assign.. and put in
ok_for_limit..\

With 2000 SF per square degree, the mean number is about 3 per fiber.  The
probability that there is no SF in reach if they are distributed randomly
is very nearly 5%.  So with 4300 to assign, you'd expect to fail about 215
times, in perfect agreement with your results.  I guess the SF are random
and not spaced so that every fiber can see one.

Bob

**Comment by forero** [comment]
Bob, I am happy to read this positive review! 

I will run the test on `/project/projectdirs/desi/datachallenge/reference_runs/18.1/fiberassign` before merging.

**Comment by forero** [comment]
Running the test I find that there are very few available fibers to start with. Only 1 or 2 for the dark tiles and 4 to 7 for the bright tiles. So I've downsampled the input `mtl` file to 10% its original size (I saved targets with `SUBPRIORITY`<0.1).

This is what we get in the old version
```
Total SKY fibers 400
Total STDSTAR fibers 111
old/tile_34170.fits - ERROR
  2807 unassigned fibers
  Petal 6 has 8/10 stdstars
Total SKY fibers 400
Total STDSTAR fibers 100
old/tile_39942.fits - ERROR
  2945 unassigned fibers
  Petal 3 has 6/10 stdstars
  Petal 8 has 9/10 stdstars
  Petal 9 has 9/10 stdstars
Total SKY fibers 400
Total STDSTAR fibers 102
old/tile_45704.fits - ERROR
  3708 unassigned fibers
  Petal 3 has 8/10 stdstars
  Petal 5 has 8/10 stdstars
  Petal 7 has 9/10 stdstars
3/3 tiles had errors
```
and the new version

```
Total SKY fibers 3146
Total STDSTAR fibers 111
new/tile_34170.fits - ERROR
  61 unassigned fibers
  Petal 6 has 8/10 stdstars
Total SKY fibers 3287
Total STDSTAR fibers 100
new/tile_39942.fits - ERROR
  58 unassigned fibers
  Petal 3 has 6/10 stdstars
  Petal 8 has 9/10 stdstars
  Petal 9 has 9/10 stdstars
Total SKY fibers 4032
Total STDSTAR fibers 102
new/tile_45704.fits - ERROR
  76 unassigned fibers
  Petal 3 has 8/10 stdstars
  Petal 5 has 8/10 stdstars
  Petal 7 has 9/10 stdstars
3/3 tiles had errors
```
So, this works as expected. STDSTAR does not change and SKY goes up to fill the available fibers. There are some unused fiber that don't have anything available.

**Comment by rncahn** [comment]
Why don't you always get 10 SS per petal?

**Comment by forero** [comment]
Well, that's the behavior in the current `master` branch. It seems that if there is nothing else available except a standard star, then it assigns that standard star. Is that right?

**Comment by forero** [comment]
Here is the output for the dark tiles
Old:
```
forero@cori08:/global/cscratch1/sd/forero/fiberassignsmalltest/dark> qa-fiberassign old/*.fits
Total SKY fibers 400
Total STDSTAR fibers 108
old/tile_01165.fits - ERROR
  2173 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 107
old/tile_06927.fits - ERROR
  2782 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 111
old/tile_11108.fits - ERROR
  2214 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 111
old/tile_16870.fits - ERROR
  2804 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 106
old/tile_18465.fits - ERROR
  3574 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 104
old/tile_24227.fits - ERROR
  4085 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 113
old/tile_28408.fits - ERROR
  3336 unassigned fibers
7/7 tiles had errors
Option --targets not specified; stopping
```
New:
```
forero@cori08:/global/cscratch1/sd/forero/fiberassignsmalltest/dark> qa-fiberassign new/*.fits
Total SKY fibers 2529
Total STDSTAR fibers 108
new/tile_01165.fits - ERROR
  44 unassigned fibers
Total SKY fibers 3120
Total STDSTAR fibers 107
new/tile_06927.fits - ERROR
  62 unassigned fibers
Total SKY fibers 2571
Total STDSTAR fibers 111
new/tile_11108.fits - ERROR
  43 unassigned fibers
Total SKY fibers 3151
Total STDSTAR fibers 111
new/tile_16870.fits - ERROR
  53 unassigned fibers
Total SKY fibers 3895
Total STDSTAR fibers 106
new/tile_18465.fits - ERROR
  79 unassigned fibers
Total SKY fibers 4424
Total STDSTAR fibers 104
new/tile_24227.fits - ERROR
  61 unassigned fibers
Total SKY fibers 3659
Total STDSTAR fibers 113
new/tile_28408.fits - ERROR
  77 unassigned fibers
7/7 tiles had errors
Option --targets not specified; stopping
```

Same result as before. STDSTAR numbers are the same while SKY numbers go up.

**Comment by rncahn** [comment]
What you showed previously had petals with too few SS.  This last output
doesn't have that problem. Perhaps the problem came from using a collection
of standard stars that had fewer than 10 available altogether on some
petals.

**Comment by sbailey** [comment]
Please fix permissions so that we can read files in `/global/cscratch1/sd/forero/fiberassignsmalltest/dark`.

What input sky file do you use?  If you are using /project/projectdirs/desi/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits then there should never be any unassigned fibers, because there should always be a sky target available (or there is a bug in my sky catalog).

i.e. have you verified that the currently unassigned fibers really have no input targets of any kind that could have been assigned?

**Comment by forero** [comment]
@sbailey I tried the new sky file and there are still unused fibers

```
forero@cori09:/global/cscratch1/sd/forero/fiberassignsmalltest/dark> qa-fiberassign new/*.fits
Total SKY fibers 2531
Total STDSTAR fibers 108
new/tile_01165.fits - ERROR
  42 unassigned fibers
Total SKY fibers 3122
Total STDSTAR fibers 107
new/tile_06927.fits - ERROR
  59 unassigned fibers
Total SKY fibers 2573
Total STDSTAR fibers 111
new/tile_11108.fits - ERROR
  40 unassigned fibers
Total SKY fibers 3145
Total STDSTAR fibers 111
new/tile_16870.fits - ERROR
  60 unassigned fibers
Total SKY fibers 3901
Total STDSTAR fibers 106
new/tile_18465.fits - ERROR
  73 unassigned fibers
Total SKY fibers 4420
Total STDSTAR fibers 104
new/tile_24227.fits - ERROR
  66 unassigned fibers
Total SKY fibers 3658
Total STDSTAR fibers 113
new/tile_28408.fits - ERROR
  78 unassigned fibers
7/7 tiles had errors
```

I will check `POTENTIALTARGET`, but a fiber might be unassigned because it collides with the other positioners if tries to get the available targets. In that case there might be available targets and still be impossible to assign.

**Comment by forero** [comment]
Results for bright tiles are similar with the new sky file
```
forero@cori09:/global/cscratch1/sd/forero/fiberassignsmalltest/bright> qa-fiberassign new/*.fits
Total SKY fibers 3149
Total STDSTAR fibers 111
new/tile_34170.fits - ERROR
  58 unassigned fibers
  Petal 6 has 8/10 stdstars
Total SKY fibers 3285
Total STDSTAR fibers 100
new/tile_39942.fits - ERROR
  63 unassigned fibers
  Petal 3 has 6/10 stdstars
  Petal 8 has 9/10 stdstars
  Petal 9 has 9/10 stdstars
Total SKY fibers 4033
Total STDSTAR fibers 102
new/tile_45704.fits - ERROR
  72 unassigned fibers
  Petal 3 has 8/10 stdstars
  Petal 5 has 8/10 stdstars
  Petal 7 has 9/10 stdstars
3/3 tiles had errors
```

**Comment by forero** [comment]
Perhaps a denser sky file would be useful to have.

**Comment by forero** [comment]
Zero available fibers for the dark tiles
```
forero@cori04:/global/cscratch1/sd/forero/fiberassignsmalltest/dark> qa-fiberassign new/*
Total SKY fibers 2572
Total STDSTAR fibers 108
new/tile_01165.fits - OK
Total SKY fibers 3185
Total STDSTAR fibers 107
new/tile_06927.fits - OK
Total SKY fibers 2612
Total STDSTAR fibers 111
new/tile_11108.fits - OK
Total SKY fibers 3206
Total STDSTAR fibers 111
new/tile_16870.fits - OK
Total SKY fibers 3972
Total STDSTAR fibers 106
new/tile_18465.fits - OK
Total SKY fibers 4485
Total STDSTAR fibers 104
new/tile_24227.fits - OK
Total SKY fibers 3736
Total STDSTAR fibers 113
new/tile_28408.fits - OK
0/7 tiles had errors
Option --targets not specified; stopping
```

```
forero@cori04:/global/cscratch1/sd/forero/fiberassignsmalltest/dark> qa-fiberassign old/*
Total SKY fibers 400
Total STDSTAR fibers 108
old/tile_01165.fits - ERROR
  2172 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 107
old/tile_06927.fits - ERROR
  2785 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 111
old/tile_11108.fits - ERROR
  2212 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 111
old/tile_16870.fits - ERROR
  2806 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 106
old/tile_18465.fits - ERROR
  3572 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 104
old/tile_24227.fits - ERROR
  4085 unassigned fibers
Total SKY fibers 400
Total STDSTAR fibers 113
old/tile_28408.fits - ERROR
  3336 unassigned fibers
7/7 tiles had errors
Option --targets not specified; stopping
```

**Comment by forero** [comment]
@sbailey @rncahn  OK to merge?

**Comment by sbailey** [comment]
OK to merge, but I'd still like to chase the details of why the nside=2048 wasn't sufficient, since those cases may also drive how we generate the real data sky locations.

**Pull request merged**
