### PR TITLE
Improve build system

### PR DESCRIPTION
**Pull request by tskisner**
This changeset replaces the inconsistent makefiles currently in use.  It has a simple top level Makefile which include a platform-specific Makefile snippet that sets the compile options.  If no platform is specified, it defaults to generic linux.  platform files for OSX and HPCPorts included.  All comments welcome.

### CODE REVIEW

**Comment by tskisner** [comment]
This update would make it possible to run on any NERSC machine, and since edison is down today Bob was hoping to use hopper...

**Comment by rncahn** [comment]
OK. There's the answer.  So the new makefile should be able to handle all
the fitsio stuff?

**Comment by rncahn** [comment]
so if I just say "make" it will know what to do?

**Comment by tskisner** [comment]
See the updated README for build instructions...

**Comment by weaverba137** [comment]
I notice there is also a product called fiberassign_sqlite.  Does that have similar problems, or is that a completely different code base?

**Comment by tskisner** [comment]
That is some other code that I know nothing about.

-T

**Pull request merged**
