### PR TITLE
sort fibers by true number rather than position in list

### PR DESCRIPTION
**Pull request by rncahn**
Now that the fibers have become a class, we want to sort the collection of fibers by the true number of the fiber, not the position in the list of the fibers.

### CODE REVIEW

**Comment by sbailey** [comment]
This defines a `sort_by_fiber_number` function but appears to not actually use it.  The actual sorting is done separately in `structs.cpp` function `read_fiber_positions`.  It also has some leftover debugging printouts to cleanup unless you think it is important to keep them for the log.

**Comment by rncahn** [comment]
Yes.  Will do.  Also I am trying to solve your problem by moving the check
on duplicates to apply only to mtl, not SS.

**Comment by rncahn** [comment]
How do I correct the pull request to make your changes?

**Comment by sbailey** [comment]
> How do I correct the pull request to make your changes?

Update the code in your branch and push again to github.  Since the PR is associated with the sort_by_fiber_number branch, any updates on github of that branch automatically apply to the PR.

**Comment by rncahn** [comment]
done

once you are happy with this, we can try my fix for the duplication issue.
Should I just push a new branch without asking for a PR so you can try out
the fix?

**Comment by sbailey** [comment]
Merging now.

It's always ok to push new branches to github to share work in progress.  Please start a new branch off of master for fixing the TARGETID duplication issue #69 .

**Comment by rncahn** [comment]
you want it off master rather than off the branch I sent for PR?

**Pull request merged**
