### PR TITLE
Add old script for patching fiberassign files (from Oct 5/2021)

### PR DESCRIPTION
**Pull request by dstndstn**
This PR adds bin/patch-fa.py, the script I ran to patch the fiberassign files the first time!  Doesn't touch any other files.

### CODE REVIEW

**Comment by araichoor** [comment]
hi @dstndstn,

my sincere apologies, I somehow totally overlooked this PR.
it would indeed be great to officially record that file.
I m thinking: maybe we could rename it? like e.g. `fba_patch_202110`?

ps: we also definitely should save the associated log files; we ll keep you updated on the preferred location.

**Comment by dstndstn** [comment]
Hi @araichoor I renamed as you suggested :)

**Comment by araichoor** [comment]
great, thanks.
I ll merge that on Monday.

in the meantime, let s also update the `doc/changes.rst` file (I can take care of that), as I try to transition to the cleaner habit of updating that file for each PR (instead of doing that when creating a tag).
see PR https://github.com/desihub/fiberassign/pull/440, that I ll probably merge on Monday.

**Comment by araichoor** [comment]
the PR https://github.com/desihub/fiberassign/pull/440 about `doc/changes.rst` got stalled by suggested improvements...
and I ve opened a separate ticket to decide how to record the log files of the patching process.

so I I m going to merge this PR (and I ll deal with the `doc/changes.rst` when closing PR https://github.com/desihub/fiberassign/pull/440).

thanks @dstndstn!

**Pull request merged**
