### PR TITLE
Fix for #249: distinguish betwen scnd and desi mask.

### PR DESCRIPTION
**Pull request by michaelJwilson**
Fix for #249:   distinguish betwen scnd and desi mask.  Runs to completion.  I don't think I broke the logic.

### CODE REVIEW

**Comment by forero** [comment]
@Srheft Does this change look good to you? Is it compatible with your current workflow for commissioning tiles?

**Comment by michaelJwilson** [comment]
Added PR number to changes.rst

**Comment by sbailey** [comment]
This PR is related to the dangling PR #248.  @geordie666 could you compare them and coordinate the solution?

@michaelJwilson `py/fiberassign/_internal.cpython-36m-x86_64-linux-gnu.so` was accidentally added.  Please remove it from your branch.

@geordie666 could you revive the BFG repo cleaner and expunge that file from the history?  You are our cleanup expert for that. :)  Thanks.  https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by michaelJwilson** [comment]
Removed _internal.so.

**Comment by Srheft** [comment]
@forero I don't use any SV type mask and data at the moment; I'll report the potential issues as soon as they come up.

**Comment by geordie666** [comment]
@sbailey: I'm not close enough to fiberassign to know whether this PR will be the correct choice for the real data for SV. This PR seems correct, though, and would supersede PR #248. So, I'd say we should merge this (if @forero finds it works with the mocks), fix any issues as they arise later, and delete PR #248 without merging it.

I'll wheel out the BFG later today and remove @michaelJwilson's `.so` file from history.

**Comment by geordie666** [comment]
I believe I have now removed @michaelJwilson's ".so" file from the general git history. Anyone attached to this thread should remove their `fiberassign` repository completely and clone a new version:
```
\rm -rf desitarget
git clone https://github.com/desihub/desitarget
```
To prevent reintroducing this file.

It would be great if the first person who does that could also confirm for me that the file `py/fiberassign/_internal.cpython-36m-x86_64-linux-gnu.so` is no longer present in their newly cloned repository.

**Comment by sbailey** [comment]
I confirm that py/fiberassign/_internal.cpython-36m-x86_64-linux-gnu.so appears to be successfully removed from the git history.

I will proceed with merging this PR and closing #248 without merging.

**Pull request merged**
