### PR TITLE
qa_related

### PR DESCRIPTION
**Pull request by Srheft**
@tskisner 
This is a branch with which I run fiberassign for cmx and sv. It includes GFA stats per camera in the qa.json; and makes the qa-fiberassign to recognize "cmx" and "sv1" surveys in adition to "main".  Although it works good enough for me to include the needed info in Tilepicker, it doesn't mean that it is tastefully written. Please don't hesitate to alter this to perfection or add these changes as part of any of your active branches.  This is just to document my changes for the record. Thanks.

@sbailey : 
you asked what magnitudes I'm using for GFA stars; I'm using `GAIA_PHOT_G_MEAN_MAG`
(see added line 596 in assign.py `gfa_gmag = gfa_data["GAIA_PHOT_G_MEAN_MAG"]` )  so although Adam mentioned [and I confirm] that only a very small percentage(<0.5%) of the GFA targets in gfa catalog are L2 [extended objects], I had ~50 tiles with at least one of these wrongfully defaulted GAIA_PHOT_G_MEAN_MAG==0. Currently, in tilepicker I only mark the tiles with 0<GAIA_PHOT_G_MEAN_MAG<7 for covered GFA stars in any of the cameras.

### CODE REVIEW

**Comment by geordie666** [comment]
For additional context:

The `L2` sources are objects in the [LSLGA catalog](http://www.legacysurvey.org/dr8/external/#lslga-large-galaxies). I intend to push a branch in `desitarget` later today that removes those from the GFA catalog.

It makes sense that although the LSLGA sources are only ~0.5% of GFAs, they would affect many tiles, as large galaxies are widely spread over the sky.

**Comment by sbailey** [comment]
For consistency with the rest of our code and to make it easier for others to edit in the future, please use 4-space indentations instead of a mix of 4 and 8.  Otherwise this looks fine.  Thanks.

**Comment by Srheft** [comment]
@sbailey 
since this branch is dedicated to enhancing fiberassign qa, it's fitting to mention that qa.json includes no info on ETC fibers and Tilepicker does not assure the observers on a healthy content for SKY_MONITOR hdu (whether all the 20 fibers have found an actual SKY[2**32] postion or N<20 fibers are pointed at SUPP_SKY or BAD_SKY"] and we easily could add it to qa.json or directly in Tilepicker.

**Comment by sbailey** [comment]
@Srheft adding ETC fiber info to qa.json would be fine, but please do that in a separate PR so that we can merge this one.  Please make the updates to the indentations for maintainability, and then we can merge this one.  Thanks.

**Pull request merged**
