### PR TITLE
Simplify plotting of fiberassign output.  

### PR DESCRIPTION
**Pull request by tskisner**
The new fba_plot script just takes a list of filenames and gets the tile and run date
information from the headers.  I will rebase this after the stuck sky work is merged.

### CODE REVIEW

**Comment by tskisner** [comment]
I also still need to add support for loading gzipped fiberassign FITS files.  I don't thing `fitsio` supports this, but can easily extract to a temporary file.

**Comment by sbailey** [comment]
Thanks; the simpler interface sounds great.  FYI fitsio supports reading gzipped files without having to do anything special.  I'm tripping on trying `fba_plot` with:
```
fba_plot /global/cfs/cdirs/desi/spectro/data/20210430/00086739/fiberassign-000046.fits.gz 
...
INFO: Plotting 1 fiberassign tile files
INFO: Creating /global/cfs/cdirs/desi/spectro/data/20210430/00086739/fiberassign-000046.pdf
WARNING: Requested run date '2021-03-17 23:20:01' is not timezone-aware.  Assuming UTC.
INFO: Loaded focalplane for time stamp 2021-03-17 23:20:01+00:00
INFO: Focalplane has 719 fibers that are stuck or broken
WARNING: Positioner at location 20 cannot move to target 616088527960015725 at (x, y) = (20.03034868815697, -80.04994954144787).  This should have been dected during assignment!
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/global/common/software/desi/users/sjbailey/fiberassign/py/fiberassign/vis.py", line 391, in plot_assignment_tile_file
    plot_assignment(
  File "/global/common/software/desi/users/sjbailey/fiberassign/py/fiberassign/vis.py", line 263, in plot_assignment
    raise RuntimeError(msg)
RuntimeError: Positioner at location 20 cannot move to target 616088527960015725 at (x, y) = (20.03034868815697, -80.04994954144787).  This should have been dected during assignment!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/users/sjbailey/fiberassign/bin/fba_plot", line 16, in <module>
    main()
  File "/global/common/software/desi/users/sjbailey/fiberassign/bin/fba_plot", line 11, in main
    run_plot(args)
  File "/global/common/software/desi/users/sjbailey/fiberassign/py/fiberassign/scripts/plot.py", line 99, in run_plot
    plot_tiles(
  File "/global/common/software/desi/users/sjbailey/fiberassign/py/fiberassign/vis.py", line 437, in plot_tiles
    pool.map(plot_tile, file_map_list)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: Positioner at location 20 cannot move to target 616088527960015725 at (x, y) = (20.03034868815697, -80.04994954144787).  This should have been dected during assignment!
```

OK to prioritize other functional tickets first, unless this PR would make debugging those easier.

**Comment by tskisner** [comment]
@sbailey, right- I think this is due to problems fixed in other PRs.  My plan was to rebase this after Dustin's PRs are merged.  Good to know fitsio supports full-file gzipped format (I thought it only supported compressed HDUs).  I will add that too.

**Comment by tskisner** [comment]
Ok, this should now be working.  Additional types of positioner states are now plotted and there is a legend.
[fiberassign-081099.pdf](https://github.com/desihub/fiberassign/files/6468727/fiberassign-081099.pdf)
fiberassign-081099
fiberassign-081099_zoom

**Comment by julienguy** [comment]
Hi Ted, an issue with imports when trying to run this:
```
fba_plot /global/cfs/cdirs/desi/spectro/data/20210511/00088038/fiberassign-081099.fits.gz 
Traceback (most recent call last):
  File "/global/common/software/desi/users/jguy/fiberassign/bin/fba_plot", line 6, in <module>
    from fiberassign.scripts.plot import parse_plot, run_plot
  File "/global/common/software/desi/users/jguy/fiberassign/py/fiberassign/scripts/plot.py", line 16, in <module>
    from ..hardware import load_hardware
  File "/global/common/software/desi/users/jguy/fiberassign/py/fiberassign/hardware.py", line 20, in <module>
    from .utils import Logger
  File "/global/common/software/desi/users/jguy/fiberassign/py/fiberassign/utils.py", line 15, in <module>
    from ._internal import (Logger, Timer, GlobalTimers, Circle, Segments, Shape,
ModuleNotFoundError: No module named 'fiberassign._internal'

```

**Comment by tskisner** [comment]
@julienguy there are some small unit test failures that I am fixing, but your issue I think is just that you need to compile the fiberassign extension.  See docs here:

https://fiberassign.readthedocs.io/en/latest/install.html#fiberassign-developer-contributor

You can either install the package or build the extension in place.

**Comment by julienguy** [comment]
Thank you @tskisner . It works fine. Two suggestions: 
 - add an argument to write the pdf file in another place than the fiberassign fits file (or not write it at all).
 - if possible: add the option to display the figure in an interactive matplotlib window.

**Comment by tskisner** [comment]
@julienguy, the script takes a list of multiple files and plots them in parallel- would an output directory option (to place all the files) be ok?  

The code writes a PDF vector image so that it can be zoomed infinitely.  A default matplotlib plot would be fixed to a given resolution (zooming would not re-draw the graphics).  If you want interactive, zoomable plotting, that would require some other graphical toolkit.  That is a large amount of work, and beyond the scope of this PR.

**Comment by sbailey** [comment]
Thanks; I'll fix one docstring after merging to not trigger branch tests again.  I tested on several recent tiles, looks good.

**Pull request merged**
