### PR TITLE
py/targets: updating for sv2 (will need eventually to make an overall…

### PR DESCRIPTION
**Pull request by araichoor**
… re-writting)

### CODE REVIEW

**Comment by forero** [comment]
@araichoor @sbailey  Maybe it's time to migrate all this code to https://github.com/desihub/desisurveyops ?

**Comment by tskisner** [comment]
Looks like the unit test runner detected that sv2 target masks do not yet exist in desitarget master.  Are they in a separate PR for desitarget?  If so, then we should merge that work first before this one.

**Comment by geordie666** [comment]
They exist:

https://github.com/desihub/desitarget/blob/master/py/desitarget/sv2/data/sv2_targetmask.yaml

and have for at least a few days. So the unit test isn't finding them for some reason.

**Comment by tskisner** [comment]
I'll test this branch locally to see what is going on.

**Comment by tskisner** [comment]
I fixed the issue in desitarget:  https://github.com/desihub/desitarget/pull/686

The sv2 data files were in the repo, but not being installed.

**Review by tskisner — COMMENTED** [review]
The changes look fine, and are no worse than all the code in there for cmx / sv1.  I do hear @forero 's comment about all of these survey bits becoming out of hand.  Let me go see if there is a quick and easy way to simplify this.  I forget the reasoning why we have these details here rather than just relying on desitarget.

**Comment by araichoor** [comment]
@tskisner : I m finding issues running at NERSC, I may have forgotten lines to add... I hope to report soon; apologies.

**Comment by tskisner** [comment]
No problem, let's not merge this branch for a few hours, I'm working on seeing if we can simplify some things.

**Comment by araichoor** [comment]
ok perfect, thanks for taking care of that; it would be really nice to clean that script; in case, I have the correct lines to add to the current version.

**Comment by tskisner** [comment]
Ok, the only reason for all the complications in `target.py` comes from the fact that for the CMX survey the bits representing how to classify targets as "science" or "standards" were very different.  It looks like for the main survey and svX these bit definitions are the same.  So, I suggest we just have 2 cases:  cmx and everything else.  If that sounds reasonable I can implement that change.

**Comment by araichoor** [comment]
I ve committed a new version of targets.py, with few additional lines to handle sv2; it should be working now.

**Comment by tskisner** [comment]
I could also save that cleanup to post-sv2, which might be better...

**Comment by araichoor** [comment]
yes, maybe better, because we re still running sv1... and it s not top-priority.

**Comment by tskisner** [comment]
Ok, as soon as the tests pass, feel free to merge and delete the branch

**Pull request merged**
