### PR TITLE
cleaning changes.rst since 1.0.0, and adding latest PR merges

### PR DESCRIPTION
**Pull request by araichoor**
This PR fixes few things in the `doc/changes.rst` file:
- it adds few PRs which were missed to be reported: I ve gone back to tag=1.0.0, not before;
- it fixes one formatting issue (for PR 428);
- it changes the tag date for 2.4.0, from 2021-05-04 to 2021-05-05, as it is the recorded github date for that tag cut (and  PR 340); I strongly suspect it just happened that this was done after midnight;
- it adds the PRs merged since the last tag cut, thus trying to shift to the good habit of updating `doc/changes.rst` for each PR, and not when creating the tag (of course, I ll add this PR to `doc/changes.rst` before merging!).

@sbailey : does it look ok to you? (I m asking as I m not familiar of how such a `doc/changes.rst` modification should be handled).

### CODE REVIEW

**Comment by sbailey** [comment]
@araichoor thanks for this doc cleanup.  To test the documentation build, run
```
python setup.py build_sphinx
```
That will reveal one typo in this PR (`316` vs. `#316`), and a number of warnings that we should also try to address even though they pre-date this PR.

This also highlights that github actions aren't running for fiberassign, and thus tests aren't being run as part of github PRs.  I think that is because .github/workflows/python-package.yml directly references "master" instead of "main" or "*" and thus isn't getting triggered.  It also looks like the github tests don't include documentation builds like other repos, thus missing the documentation problems that arisen (references to files that no longer exist, and documents not included in the "toctree" table of contents).  Let's try to restore github tests, adding documentation builds, as part of this PR.  If that gets too messy, we can spin it off to a separate PR.

Back to doc/changes.rst workflow.  My preferred procedure (which I don't follow very well...) is that after each PR is merged, immediately update doc/changes.rst directly in main with the info for the PR that you just merged.  If there is only one PR active at a time, the update could also be done as part of the PR itself before merging, but that becomes a hassle if there are multiple active PRs because they are all wanting to update changes.rst with a new line that creates merge conflicts and I find it easier to just add it post-merge.

**Comment by araichoor** [comment]
thanks a lot for the inputs! (and the check).

I ve corrected the formatting bug (for PR 316).

about the tests/github actions: yes, it d be nice to get all that cleaner; but I m quite ignorant about those, so I might need help here.

first, if I understand your message, shall I replace "master" by "\*" here (I checked that desispec and desitarget use "\*"):
https://github.com/desihub/fiberassign/blob/53199d2a8cd01240c1308c78a70bce0ddddaedf1/.github/workflows/test.yml#L4-L7

for the docs test, shall I copy this part of the desispec file?
https://github.com/desihub/desispec/blob/b8ce9623c354252d636a3c3843096f7e8cb2233e/.github/workflows/python-package.yml#L94-L116
desitarget has similar lines, except for the python-version, which is `3.8` (not as a string, btw).

I notice that desispec and desitarget have a "style check" part, which fiberassign does not have.

lastly, about the warnings/errors from `python setup.py build_sphinx`, I don t really know what to do.
there is this error/warning:
```
reading sources... [100%] script_fba_plot_results                                                                                                                                                   
WARNING: autodoc: failed to import class 'TargetTree' from module 'fiberassign.targets'; the following exception was raised:
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/util/inspect.py", line 448, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'fiberassign.targets' has no attribute 'TargetTree'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2780, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/util/inspect.py", line 464, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: TargetTree

/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_results.rst:6: WARNING: Include file '/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/bin/fba_plot_results' not found or reading it failed
```

and those warning:
```
checking consistency... /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_merge_results.rst: WARNING: document isn't included in any toctree
/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_qa.rst: WARNING: document isn't included in any toctree
/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_results.rst: WARNING: document isn't included in any toctree
/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_run.rst: WARNING: document isn't included in any toctree
/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_run_qa.rst: WARNING: document isn't included in any toctree
```

**Comment by sbailey** [comment]
> thanks a lot for the inputs! (and the check).
> 
> I ve corrected the formatting bug (for PR 316).
> 
> about the tests/github actions: yes, it d be nice to get all that cleaner; but I m quite ignorant about those, so I might need help here.
> 
> first, if I understand your message, shall I replace "master" by "*" here (I checked that desispec and desitarget use "*"):
> 
> https://github.com/desihub/fiberassign/blob/53199d2a8cd01240c1308c78a70bce0ddddaedf1/.github/workflows/test.yml#L4-L7
> 
> for the docs test, shall I copy this part of the desispec file? https://github.com/desihub/desispec/blob/b8ce9623c354252d636a3c3843096f7e8cb2233e/.github/workflows/python-package.yml#L94-L116 desitarget has similar lines, except for the python-version, which is `3.8` (not as a string, btw).

I think "yes" to all of those.

> 
> I notice that desispec and desitarget have a "style check" part, which fiberassign does not have.

I consider that optional.  Add it if you want, but also ok if you don't add it here/now so that we don't have too much scope creep on this PR.

> lastly, about the warnings/errors from `python setup.py build_sphinx`, I don t really know what to do. there is this error/warning:
> 
> ```
> reading sources... [100%] script_fba_plot_results                                                                                                                                                   
> WARNING: autodoc: failed to import class 'TargetTree' from module 'fiberassign.targets'; the following exception was raised:
> Traceback (most recent call last):
>   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/util/inspect.py", line 448, in safe_getattr
>     return getattr(obj, name, *defargs)
> AttributeError: module 'fiberassign.targets' has no attribute 'TargetTree'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
>     obj = attrgetter(obj, mangled_name)
>   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 332, in get_attr
>     return autodoc_attrgetter(self.env.app, obj, name, *defargs)
>   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2780, in autodoc_attrgetter
>     return safe_getattr(obj, name, *defargs)
>   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/sphinx/util/inspect.py", line 464, in safe_getattr
>     raise AttributeError(name) from exc
> AttributeError: TargetTree

We may need @weaverba137 or @tskisner for this one.  It appears that TargetTree isn't directly referenced in the python code, but is part of the C++ code that may be exposed to the python code via the pybind11 wrappers and that is confusing sphinx.

> 
> /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_results.rst:6: WARNING: Include file '/global/u2/r/raichoor/software_dev/fiberassign_doc_changes/bin/fba_plot_results' not found or reading it failed
> ```

doc/script_fba_plot_results.rst has `.. literalinclude:: ../bin/fba_plot_results` but that file doesn't exist.  I haven't dug deeper to see if it has just been removed/renamed, or what the documentation should refer to if anything.

> 
> and those warning:
> 
> ```
> checking consistency... /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_merge_results.rst: WARNING: document isn't included in any toctree
> /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_qa.rst: WARNING: document isn't included in any toctree
> /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_plot_results.rst: WARNING: document isn't included in any toctree
> /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_run.rst: WARNING: document isn't included in any toctree
> /global/u2/r/raichoor/software_dev/fiberassign_doc_changes/doc/script_fba_run_qa.rst: WARNING: document isn't included in any toctree
> ```

I think sphinx's rules are that every .rst file (except index.rst) has to be referenced in a .. toctree:: section of another file (or linked to them or included by them or something) so that you can always navigate to every file starting from the top level index.  These cases might be leftovers that could be deleted, or perhaps some other documentation needs to reference them.

**Comment by araichoor** [comment]
again, thanks for the answers.
I ve:
- changed the "master" to "\*", modifying a bit the lines, with copying the ones from desispec;
- copied the #L94-L116 from the desispec `.github/workflows/test.yml`.

**Comment by araichoor** [comment]
.. and I got this error:
https://github.com/desihub/fiberassign/actions/runs/3315188513/workflow
```
Invalid workflow file
The workflow is not valid. .github/workflows/test.yml (Line: 92, Col: 5): Unexpected value 'docs'
```

I suspect it s some indentation issue: the "original" fiberassign `test.yml` file uses 2-spaces indentation in the `jobs` part, against 4-spaces indentation for what I ve added (`docs`).
shall I move everything to 4-spaces indentation?

there also is a large commented section (`macos`); don t know if that matters here.

**Comment by sbailey** [comment]
@araichoor indeed it was a config file indentation issue; the "docs:" level entry needed to be two spaces, at the same level as "linux:", not 4-spaces under the hierarchy of "linux:".

So now doc tests are running, but are failing do to not finding astropy, numpy, etc.  Please try something like this section of the desispec/doc/conf.py to flag which external modules it should not worry about (or otherwise they need to be installed as part of the doc test config, which is possible but a bit overkill).
```python
# This value contains a list of modules to be mocked up. This is useful when
# some external dependencies are not met at build time and break the
# building process.
from importlib import import_module
autodoc_mock_imports = []
for missing in ('astropy', 'astropy.modeling', 'desimodel', 'desitarget',
                'desiutil', 'fitsio', 'healpy',
                'matplotlib', 'numba', 'numpy', 'redrock', 'requests',
                'scipy', 'speclite', 'specter', 'sqlalchemy', 'yaml', 'specex'):
    try:
        foo = import_module(missing)
    except ImportError:
        autodoc_mock_imports.append(missing)
```

**Comment by araichoor** [comment]
one question before I touch those files: is there a way to locally check things, before pushing the commit?
ie is there some kind of "python test" command I could run?
to avoid a possible long list of test-n-try commits...

then, about the python packages:
sure, I can copy the `autodoc_mock_imports.append(missing)` lines you pointed to.
from the tests, it looks like it s unhappy with `numpy` and `astropy`; but I suspect that if I include those, then it may be unhappy with other ones further in the process.. that gets back to my first question, on to how to "debug" that on my local checkout.

also, if relevant, I notice that those lines are commented out:
https://github.com/desihub/fiberassign/blob/49b391e661cc5b172a7e1084052cf9b8e2dfe970/doc/conf.py#L67-L74
whereas they are not in desispec/doc/conf.py; by any chance could re-enabling those do the trick?

another comment, looking at the checks: I see an error with DESIMODEL/master; I probably should change "master" to "main" here, no?
https://github.com/desihub/fiberassign/blob/49b391e661cc5b172a7e1084052cf9b8e2dfe970/.github/workflows/test.yml#L19

**Comment by weaverba137** [comment]
I see that the fiberassign test infrastructure has diverged significantly from other DESI packages.  Normally the unit tests would include a test of the documentation:
```
python -m pip install --upgrade pip wheel Sphinx
sphinx-build -W --keep-going -b html doc doc/_build/html
```
which you can certainly also run locally.

**Comment by weaverba137** [comment]
Also, for the commented-out lines in the doc/conf.py file, those are useful for creating documentation links to objects imported from other packages, but its presence or absence shouldn't cause a problem.  I would get local tests running first then experiment with including that configuration.

**Comment by sbailey** [comment]
Thanks for the extra info, @weaverba137 .

@araichoor to mimic the github doc test environment, I think you'd need to setup a minimalist conda environment that does *not* have numpy, astropy, etc. before running
```
python -m pip install --upgrade pip wheel Sphinx
sphinx-build -W --keep-going -b html doc doc/_build/html
```

**Comment by araichoor** [comment]
thanks @weaverba137!
just, I notice that those lines are here: https://github.com/desihub/fiberassign/blob/49b391e661cc5b172a7e1084052cf9b8e2dfe970/.github/workflows/test.yml#L71-L75
doesn t that mean that those tests are actually run?

and I indeed have difficulties to reproduce those tests on my local checkout.
e.g. from a "clean" environment:
```
raichoor@cori12:~/software_dev/fiberassign_doc_changes> python -m pip install --upgrade pip wheel Sphinx
/usr/bin/python: No module named pip
```
and from a `godesi master` environment:
```
raichoor@cori12:~/software_dev/fiberassign_doc_changes> python -m pip install --upgrade pip wheel Sphinx 
...
Installing collected packages: Pygments, wheel, Sphinx, pip
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx-tabs 3.3.1 requires sphinx<5,>=2, but you have sphinx 5.3.0 which is incompatible.
autodocsumm 0.2.8 requires Sphinx<5.0,>=2.2, but you have sphinx 5.3.0 which is incompatible.
Successfully installed Pygments-2.13.0 Sphinx-5.3.0 pip-22.3 wheel-0.37.1
```

and, if I run `sphinx-build -W --keep-going -b html doc doc/_build/html`:
-from a clean environment, I ve tons of errors like
```
reading sources... [100%] usage                                                                                                                                                                    
WARNING: autodoc: failed to import function 'utils.option_list' from module 'fiberassign'; the following exception was raised:
No module named 'fiberassign._internal'
```
- from a `godesi master` environment, it doesn t see the "missing" astropy, numpy, etc.

so I m a bit lost here, sorry..

**Comment by weaverba137** [comment]
@araichoor, I was not looking at your branch, sorry about that.

Is your local checkout on your laptop/workstation or at NERSC? The laptop/workstation environment is much easier to set up cleanly and isolated from other environments.

It's a *good thing* that you did not find `pip` at NERSC, because that could potentially have overwritten DESI environments.

**Comment by araichoor** [comment]
oops, sorry for having dummily run this `python -m pip install --upgrade pip wheel Sphinx` command from nersc!
I didn t realize the potential implications of that..

**Comment by araichoor** [comment]
and, again, thanks @weaverba137 for the suggestion to run locally.
from a "base" conda environment, it looks Iike adding these lines in the `doc/conf.py`  remove the errors:
```
autodoc_mock_imports = []
for missing in ('astropy', 'numpy', 'fitsio', 'healpy',
        'desitarget.skyhealpixs'):
    try:
        foo = import_module(missing)
    except ImportError:
        autodoc_mock_imports.append(missing)
```
shall I go and commit that?

**Comment by araichoor** [comment]
for info, I ll go ahead and test the changes I suggested in my previous comment.

**Comment by araichoor** [comment]
it looks like my tries are a failure...
the Linux tests fail with this error:
```
    platescale = dmio.load_platescale()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/desimodel/io.py", line 376, in load_platescale
    _platescale = np.loadtxt(infile, usecols=[0, 1, 6, 7, 8], dtype=columns)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1318, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: invalid column index 8 at row 1 with 8 columns
```
I m not really sure the reason of that failure.
for what is worth, the desimodel code in question:
https://github.com/desihub/desimodel/blob/51a58cbc8e8040323f514f5966a896a520978172/py/desimodel/io.py#L377-L388

the Doc test fails with:
```
WARNING: autodoc: failed to import function 'utils.option_list' from module 'fiberassign'; the following exception was raised:
No module named 'fiberassign._internal'
```
same, here I don t really know what should be done..

apologies for being quite useless here.

**Comment by araichoor** [comment]
Doc test failure:
```
AttributeError: module 'fiberassign.targets' has no attribute 'TargetTree'
```

it s probably linked to this commit which removed `TargetTree`: https://github.com/desihub/fiberassign/commit/43ed986634b664560294ebf818d2f86c068a7d71

and I m not sure if the way to cure that is to remove/modify these lines in `doc/reference.rst`:
```
After loading all the data, we usually want to index these targets in a hierarchical triangular mesh (HTM) structure for fast querying of targets that lie within some radius of a sky location. This is accomplished by creating a TargetTree object from the Targets instance:

.. autoclass:: fiberassign.targets.TargetTree
    :members:
```

**Comment by weaverba137** [comment]
@araichoor, I was just talking to @sbailey about this PR, and I will take a look.

**Comment by araichoor** [comment]
that would be awesome, thanks; I apologize for being quite useless here...

**Comment by weaverba137** [comment]
While I'm working on the *technical* aspects of compiling the documentation, what is the *operational* replacement for `fiberassign.targets.TargetTree`?  In other words: what language should we replace this with:
```
After loading all the data, we usually want to index these targets in a hierarchical triangular mesh (HTM) structure for fast querying of targets that lie within some radius of a sky location.  This is accomplished by creating a `TargetTree` object from the `Targets` instance:

.. autoclass:: fiberassign.targets.TargetTree
    :members:
```
This may involve reviewing the merge commit history to figure out who removed `fiberassign.targets.TargetTree`.

From my end, I have been able to complete a clean documentation build at NERSC.  It involved these steps:

1. Clean check out from GitHub, switch to `doc_changes` branch.
2. `python setup.py build_ext --inplace`
3. Comment out the section about `TargetTree`.
4. Add the `script_fba_*.rst` files to the `index.rst`; Sphinx does not like "dangling" `*.rst` files that are not linked to by any other `*.rst` file.
5. Comment out a small section of `script_fba_plot_results.rst`.
6. `sphinx-build -W --keep-going -b html doc doc/_build/html`

Getting this to work in the GitHub Actions runners is a separate issue, but at least we have an existence proof that the documentation *can* build cleanly.

**Comment by araichoor** [comment]
"_what is the operational replacement for fiberassign.targets.TargetTree? In other words: what language should we replace this with:_"
=> @dstndstn did this commit: https://github.com/desihub/fiberassign/commit/43ed986634b664560294ebf818d2f86c068a7d71.

**Comment by weaverba137** [comment]
That was easy.  OK, @dstndstn, could you please provide replacement text for us?

**Comment by araichoor** [comment]
@weaverba137 : for info, independently of this PR, I m thinking of defining a new fiberassign tag today (as I m going to design some tiles with the latest code version).

I think it s not a problem, but I just wanted to double-check that creating a tag won t complicate things for the work in this PR.

**Comment by weaverba137** [comment]
That should not be a problem. We may need to resync `changes.rst` after, but that should be easy at this point.

**Comment by araichoor** [comment]
perfect, thanks for the confirmation!

**Comment by weaverba137** [comment]
All GitHub tests are now passing, but it might be worthwhile to sync the test infrastructure with other DESI packages to reduce maintenance overhead.  This would mostly involve changes to the test.yml file itself and consolidating the list of required packages.

Some of the changes required to work on GitHub:

* Pin `numpy<1.22`; there are several other DESI packages that require this.
* Install `requests`.  This is an indirect dependency brought in by `desitarget`.
* Like on NERSC, minimally (`build_ext` *versus* `install`) compile the package before building documentation.

**Comment by dstndstn** [comment]
> That was easy. OK, @dstndstn, could you please provide replacement text for us?

We switched from TargetTree to using a scipy.spatial.KDTree.  So I guess it could say

>  After loading all the data, we build a `scipy.statial.KDTree` to index these targets spatially for fast querying of targets that lie within some radius of a sky location.

**Comment by araichoor** [comment]
thanks @weaverba137 for solving all the failures!

"_it might be worthwhile to sync the test infrastructure with other DESI packages to reduce maintenance overhead. This would mostly involve changes to the test.yml file itself and consolidating the list of required packages._"
=> is the goal to have this done in this PR? who could take care of that? (happy to help, but I still have very limit knowledge in those things).

apart from that, if I m correct, the following remain:
- update `doc/reference.rst` with the text suggested by @dstndstn 
- resync `doc/changes.rst` with the main version which has been modified in the meantime.
right?

**Comment by weaverba137** [comment]
Let me work on this a little bit more today, it won't take me long.  I'll also resolve conflicts in changes.rst.  Then we can create other issues related to maintainability.

**Comment by araichoor** [comment]
as I m curious to learn, I follow your commits :)
in case relevant: I notice here https://github.com/desihub/fiberassign/pull/440/commits/e8a77155503f5e654d25b764ec41547f18908c93 that it s actually the `numpy 1.23 test` which has been removed, not the `numpy 1.22 test` as mentionned in the commit comment; don t know if that matters...

**Comment by weaverba137** [comment]
I am still testing.

**Comment by weaverba137** [comment]
@sbailey, *et al.*, I think this is ready for any final reviews you want to do.

**Review by dstndstn — APPROVED** [review]
This all looks  fine to me

**Comment by araichoor** [comment]
is everyone happy with PR? (@sbailey)
I am of course happy, thanks @weaverba137 for the code changes!

(btw, @weaverba137, you wrote: "_Then we can create other issues related to maintainability._" => I ll let that on you / @sbailey, as, as you ve understood, I don t master the subtleties here).

**Comment by weaverba137** [comment]
@araichoor, indeed, I can handle creating the maintainability issues.

I also agree this is ready to be merged.

**Comment by weaverba137** [comment]
Please go ahead and merge.  I have spoken to Stephen about this.

**Comment by araichoor** [comment]
ok perfect, thanks!!

**Pull request merged**
