### PR TITLE
Change print to log

### PR DESCRIPTION
**Pull request by echaussidon**
Hi, 

In order to remove messages from fiberassign when running the fiberassignment, I change `print` to `logger.info` using the internal logger of fiberassign.

### CODE REVIEW

**Comment by araichoor** [comment]
first thing: I m not a github expert, but it does not sound good to have a branch named "main", no?
maybe safer to rename your branch to something else?

**Comment by araichoor** [comment]
in the same spirit, what is this commit: https://github.com/desihub/fiberassign/pull/439/commits/4e49f26dc8f5520150cbfa7461b859feffcf0d57("Merge branch 'desihub:main' into main") ?

**Comment by echaussidon** [comment]
Hi Anand, 

the name of my branch is not a problem since I forked the package, the my branch is echaussidon/main following desihub/main branch !

the first is when I update my main branch in my fork from the main branch of desihub (that you update earlier this week)

**Comment by araichoor** [comment]
ok great, thanks for the answers.
I ll merge it then.

**Pull request merged**
